mutation CreateUser($id: UUID!, $email: String!, $name: String, $dni: String, $phone: String) @auth(level: NO_ACCESS) {
  users_insert(
    data: {
      id: $id
      email: $email
      name: $name
      dni: $dni
      phone: $phone
    }
  )
}