mutation CreateUser($id: String!, $email: String!, $name: String, $dni: String, $phone: String, $role: String) @auth(level: PUBLIC) {
  users_insert(
    data: {
      id: $id
      email: $email
      name: $name
      dni: $dni
      phone: $phone
      role: $role
    }
  )
}

mutation updateUserRole(
  $id: String!, $role: String!
)  @auth(level: PUBLIC) {
  users_update(id: $id, data: {role: $role})
}


