query ListProducts @auth(level: PUBLIC) {
  productss(limit: 50) {
    id
    name
    description
    price
    image
    category
  }
}
query GetProduct @auth(level: PUBLIC) {
  products(id: "550e8400-e29b-41d4-a716-446655440000") {
    id
    name
    description
    price
    image
    category
  }
}
query ListProductsByCategory @auth(level: PUBLIC) {
  productss(where: {category: {eq: "Electronics"}}) {
    id
    name
    description
    price
    image
    category
  }
}
query ListUsers @auth(level: PUBLIC) {
  userss(limit: 50) {
    id
    name
    email
    createdAt
    dni
    phone
  }
}

query getUserById($id: String!) @auth(level: PUBLIC) {
  users(id: $id ) {
    id
    name
    email
    role
    createdAt
    dni
    phone
  }
}

query listSales @auth(level: PUBLIC) {
  sales {
    items {
      id
      saleDate
      total
      user {
        name
        email
      }
    }
  }

  saleDetails {
    items {
      saleId
      quantity
      subtotal
      product {
        name
        price
      }
    }
  }

  shipments {
    items {
      saleId
      address
      city
      status
      shippedAt
      deliveredAt
    }
  }
}
