
query ListProducts {
  products {
    id
    name
    description
    price
    image
    category
    data_ai_hint
  }
}

query GetProductById($id: String!) {
  products(id: { eq: $id }) {
    id
    name
    description
    price
    image
    category
    data_ai_hint
  }
}
