query listSales {
  sales(orderBy: {saleDate: "DESC"}) {
    id
    saleDate
    total
    user {
      id
      name
      email
    }
    shipment {
      id
      status
      address
      city
    }
    details {
      id
      quantity
      subtotal
      product {
        id
        name
        price
      }
    }
  }
}
