
query listSales {
  sales {
    id
    saleDate
    total
    user {
      name
    }
    details {
      id
      quantity
      subtotal
      product {
        name
      }
    }
    shipment {
      address
      city
      status
    }
  }
}
