query ListUsers @auth(level: ADMIN) {
  userss {
    id
    name
    email
    role
    createdAt
    dni
    phone
  }
}

query getUserById($id: String!) @auth(level: ADMIN) {
  users(id: $id) {
    id
    name
    email
    role
    createdAt
    dni
    phone
  }
}
