query listUsers {
  userss {
    id
    name
    email
    role
    createdAt
    dni
    phone
  }
}

query getUserById($id: String!) {
  users(id: $id) {
    id
    name
    email
    role
    createdAt
    dni
    phone
  }
}
