
query listUsers {
    users {
        id
        name
        email
        role
        createdAt
        dni
        phone
    }
}

query getUserById($id: String!) {
    users(id: { eq: $id }) {
        id
        name
        email
        role
        createdAt
        dni
        phone
    }
}
