
type Products @table(name: "products") {
  id: String! @pk
  name: String!
  description: String
  price: Float!
  image: String
  category: String
  data_ai_hint: String
  createdAt: Timestamp
  updatedAt: Timestamp
}
