type Sales @table(name: "sales") {
  id: UUID! @id
  userId: String! @col(name: "user_id")
  user: Users! @ref(fields: "userId", references: "id")
  saleDate: Date! @col(name: "sale_date") @default(expr: "request.time")
  total: Float!
  details: [SaleDetails]! @ref(references: "saleId")
  shipment: Shipments @ref(references: "saleId")
}
