
type SaleDetails @table(name: "sale_details") {
  id: String! @pk
  saleId: String!
  productId: String!
  quantity: Int!
  subtotal: Float!
  sale: Sales @belongsTo(foreignKey: "saleId", references: "id")
  product: Products @belongsTo(foreignKey: "productId", references: "id")
}
