type Sales @table(name: "sales") {
  id: UUID! @id
  userId: String!
  saleDate: Date!
  total: Float!
  user: Users @relation(field: "userId")
  details: [SaleDetails] @relation(on: "saleId")
  shipment: Shipments @relation(on: "saleId")
}
