
"""
Represents the shipping information for a sale.
"""
type Shipments @table(name: "shipments") {
  id: UUID!
  saleId: UUID! @col(name: "sale_id") @unique
  sale: Sales! @ref(references: "id")
  address: String!
  city: String!
  country: String!
  trackingNumber: String @col(name: "tracking_number")
  shippedDate: Timestamp @col(name: "shipped_date")
  status: String! @col(default: "'preparing'") # e.g., preparing, shipped, delivered
}
