
type Shipments @table(name: "shipments") {
  id: String! @pk
  saleId: String!
  address: String!
  city: String!
  status: String!
  createdAt: Timestamp
  updatedAt: Timestamp
  sale: Sales @belongsTo(foreignKey: "saleId", references: "id")
}
