type Shipments @table(name: "shipments") {
  id: UUID! @id
  saleId: UUID! @unique
  address: String!
  city: String!
  status: String! @default(value: "pending")
  shippedAt: Timestamp
  deliveredAt: Timestamp
  sale: Sales @relation(field: "saleId")
}
