
query GetCartByUserId($userId: ID!) {
  shopping_carts(filter: { user_id: { eq: $userId } }) {
    id
    shopping_cart_itemsCollection {
      id
      quantity
      product {
        id
        name
        price
        image
        description
        category
      }
    }
  }
}

mutation AddOrUpdateCartItem($cart_id: ID!, $product_id: ID!, $quantity: Int!) {
  shopping_cart_items_insert(
    value: {
      cart_id: $cart_id,
      product_id: $product_id,
      quantity: $quantity
    }
  ) {
    id
  }
}

mutation RemoveCartItem($itemId: ID!) {
  shopping_cart_items_delete(
    filter: {
      id: { eq: $itemId }
    }
  ) {
    id
  }
}

mutation CreateCartForUser($userId: ID!) {
    shopping_carts_insert(value: { user_id: $userId }) {
        id
    }
}
