query GetCartByUserId($userId: UUID!) @auth(level: USER) {
    shoppingCartsCollection(
        filter: {
            userid: {
                _eq: $userId
            }
        },
        first: 1
    ) {
        id
        items {
            id
            quantity
            product {
                id
                name
                price
                image
                description
                category
            }
        }
    }
}
