type Products @table {
  id: UUID! 
  name: String!
  description: String
  price: Float!
  image: String
  category: String
}

type Users @table {
  id: UUID! 
  name: String
  email: String! @unique
  createdAt: Timestamp!
}
