type Products @table {
  id: UUID!
  name: String!
  description: String
  price: Float!
  image: String
  category: String
}

type Users @table(name: "users", key: "id") {
  id: String!
  name: String
  email: String! @unique
  dni: String
  phone: String
  role: String @default(value: "user")
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}

type Sales @table(name: "sales", key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  userId: String! @col(name: "user_id")
  user: Users! @ref(fields: "userId", references: "id")
  saleDate: Date! @col(name: "sale_date") @default(expr: "request.time")
  total: Float!
}

type SaleDetails @table(name: "sale_details", key: "id") {
  id: UUID! @default(expr: "uuidV4()")
  saleId: UUID! @col(name: "sale_id")
  sale: Sales! @ref(fields: "saleId", references: "id")
  productId: UUID! @col(name: "product_id")
  product: Products! @ref(fields: "productId", references: "id")
  quantity: Int!
  subtotal: Float!
}

type Shipments @table{
  sale: Sales! @unique
  address: String!
  city: String!
  status: String! @default(value: "pending")
  shippedAt: Timestamp @col(name: "shipped_at")
  deliveredAt: Timestamp @col(name: "delivered_at")
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}