type Users @table(name: "users") {
  id: String!
  name: String
  email: String! @unique
  dni: String
  phone: String
  role: String @col(default: "'user'")
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}
